version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/aas-web-ui"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"